name: Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current release
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Install NodeJs 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Cache dependencies and build outputs to improve workflow execution time
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
